import type { Country, Program, University } from "./types";

const now = new Date().toISOString();

export const seedCountries: Country[] = [
  {
    id: "uk", name: "United Kingdom", flag: "🇬🇧", currency: "GBP",
    shortDescription: "World-class universities with 2-year PSW.",
    avgTuition: "£12,000 – £25,000", avgLivingCost: 12000, workRights: "20 hrs/week", pswDuration: "2 years",
    prPossibility: "Medium", popularIntakes: ["January", "September"], processingTime: "3–4 weeks",
    ielts: true, pte: true, duolingo: false, moi: true, minGpa: 2.5, gapAccepted: true, maxGap: 10, backlogsAccepted: true,
    visaFee: 524, medical: false, biometrics: true, tbTest: true, bankStatement: true, bankBalance: 12000,
    sponsorAllowed: true, loanAccepted: true,
    dependentAllowed: false, spouseCanWork: false,
    status: "Verified", updatedAt: now,
  },
  {
    id: "au", name: "Australia", flag: "🇦🇺", currency: "AUD",
    shortDescription: "Great PSW and high-quality education.",
    avgTuition: "A$20,000 – A$45,000", avgLivingCost: 21000, workRights: "48 hrs/fortnight", pswDuration: "2–4 years",
    prPossibility: "High", popularIntakes: ["February", "July"], processingTime: "4–8 weeks",
    ielts: true, pte: true, duolingo: false, moi: false, minGpa: 2.7, gapAccepted: true, maxGap: 7, backlogsAccepted: true,
    visaFee: 710, medical: true, biometrics: true, tbTest: false, bankStatement: true, bankBalance: 24505,
    sponsorAllowed: true, loanAccepted: true,
    dependentAllowed: true, spouseCanWork: true, childrenAllowed: true,
    status: "Verified", updatedAt: now,
  },
  {
    id: "ca", name: "Canada", flag: "🇨🇦", currency: "CAD",
    shortDescription: "Affordable tuition and strong PR pathway.",
    avgTuition: "C$15,000 – C$35,000", avgLivingCost: 15000, workRights: "24 hrs/week", pswDuration: "Up to 3 years",
    prPossibility: "High", popularIntakes: ["January", "May", "September"], processingTime: "8–12 weeks",
    ielts: true, pte: true, duolingo: true, moi: false, minGpa: 2.5, gapAccepted: true, maxGap: 5, backlogsAccepted: true,
    visaFee: 235, medical: true, biometrics: true, tbTest: false, bankStatement: true, bankBalance: 20635,
    sponsorAllowed: true, loanAccepted: true,
    dependentAllowed: true, spouseCanWork: true, childrenAllowed: true,
    status: "Verified", updatedAt: now,
  },
  {
    id: "us", name: "United States", flag: "🇺🇸", currency: "USD",
    shortDescription: "Top-ranked universities, OPT/STEM-OPT pathway.",
    avgTuition: "$25,000 – $60,000", avgLivingCost: 18000, workRights: "20 hrs/week (on-campus)", pswDuration: "1–3 years (OPT)",
    prPossibility: "Medium", popularIntakes: ["January", "August"], processingTime: "Varies",
    ielts: true, pte: true, duolingo: true, moi: false, minGpa: 3.0, gapAccepted: true, maxGap: 5, backlogsAccepted: true,
    visaFee: 185, medical: false, biometrics: true, tbTest: false, bankStatement: true, bankBalance: 30000,
    sponsorAllowed: true, loanAccepted: true,
    dependentAllowed: true, spouseCanWork: false,
    status: "Verified", updatedAt: now,
  },
  {
    id: "de", name: "Germany", flag: "🇩🇪", currency: "EUR",
    shortDescription: "Low/no tuition at public universities.",
    avgTuition: "€0 – €20,000", avgLivingCost: 11000, workRights: "120 full days/year", pswDuration: "18 months",
    prPossibility: "High", popularIntakes: ["April", "October"], processingTime: "6–12 weeks",
    ielts: true, pte: true, duolingo: false, moi: false, minGpa: 2.5, gapAccepted: true, maxGap: 4, backlogsAccepted: true,
    visaFee: 75, medical: false, biometrics: true, tbTest: false, bankStatement: true, bankBalance: 11208,
    sponsorAllowed: false, loanAccepted: true,
    dependentAllowed: true, spouseCanWork: true, childrenAllowed: true,
    status: "Verified", updatedAt: now,
  },
];

export const seedUniversities: University[] = [
  {
    id: "uk-coventry", name: "Coventry University", countryId: "uk", city: "Coventry", type: "Public",
    ranking: "601-800", partner: true, priority: "High",
    ugAccepted: true, pgAccepted: true, minGpaUg: 2.5, minGpaPg: 2.8, threeYrBachelor: true, gapAccepted: true, maxGap: 10, backlogsAccepted: true,
    nepaliMoiUnis: ["Tribhuvan University", "Kathmandu University"],
    ieltsRequired: true, ieltsOverall: 6.0, ieltsBand: 5.5, pteRequired: false, moi: true, g12Waiver: true,
    applicationFee: 0, avgTuition: 16800, scholarshipAvailable: true, scholarshipAmount: 4000, scholarshipType: "Automatic",
    visaConfidence: "High", status: "Verified", updatedAt: now,
  },
  {
    id: "uk-greenwich", name: "University of Greenwich", countryId: "uk", city: "London", type: "Public",
    ugAccepted: true, pgAccepted: true, minGpaUg: 2.4, minGpaPg: 2.7,
    ieltsRequired: true, ieltsOverall: 6.0, moi: true,
    applicationFee: 0, avgTuition: 17500, scholarshipAvailable: true, scholarshipAmount: 3000, scholarshipType: "Merit-based",
    visaConfidence: "Medium", status: "Verified", updatedAt: now,
  },
  {
    id: "au-deakin", name: "Deakin University", countryId: "au", city: "Melbourne", type: "Public",
    ranking: "201-250", partner: true, priority: "High",
    ugAccepted: true, pgAccepted: true, minGpaUg: 2.7, minGpaPg: 3.0,
    ieltsRequired: true, ieltsOverall: 6.5, ieltsBand: 6.0, moi: false,
    applicationFee: 100, avgTuition: 36000, scholarshipAvailable: true, scholarshipAmount: 5000, scholarshipType: "Merit-based",
    visaConfidence: "High", status: "Verified", updatedAt: now,
  },
  {
    id: "au-latrobe", name: "La Trobe University", countryId: "au", city: "Melbourne", type: "Public",
    ugAccepted: true, pgAccepted: true, minGpaUg: 2.5,
    ieltsRequired: true, ieltsOverall: 6.5, moi: false,
    avgTuition: 34000, scholarshipAvailable: true, scholarshipAmount: 6000, scholarshipType: "Percentage",
    visaConfidence: "Medium", status: "Verified", updatedAt: now,
  },
  {
    id: "ca-cape-breton", name: "Cape Breton University", countryId: "ca", city: "Sydney, NS", type: "Public",
    ugAccepted: true, pgAccepted: true, minGpaUg: 2.5,
    ieltsRequired: true, ieltsOverall: 6.5, ieltsBand: 6.0, duolingo: true,
    avgTuition: 21000, scholarshipAvailable: false,
    visaConfidence: "Medium", status: "Verified", updatedAt: now,
  },
  {
    id: "ca-york", name: "York University", countryId: "ca", city: "Toronto", type: "Public",
    ranking: "401-500", priority: "Medium",
    ugAccepted: true, pgAccepted: true, minGpaUg: 3.0, minGpaPg: 3.3,
    ieltsRequired: true, ieltsOverall: 6.5, duolingo: true,
    avgTuition: 32000, scholarshipAvailable: true, scholarshipAmount: 4000, scholarshipType: "Merit-based",
    visaConfidence: "High", status: "Verified", updatedAt: now,
  },
  {
    id: "us-asu", name: "Arizona State University", countryId: "us", city: "Tempe, AZ", type: "Public",
    ranking: "201-250", priority: "High",
    ugAccepted: true, pgAccepted: true, minGpaUg: 3.0, minGpaPg: 3.0,
    ieltsRequired: true, ieltsOverall: 6.5, duolingo: true,
    avgTuition: 31000, scholarshipAvailable: true, scholarshipAmount: 8000, scholarshipType: "Merit-based",
    visaConfidence: "Medium", status: "Verified", updatedAt: now,
  },
  {
    id: "de-tu-munich", name: "Technical University of Munich", countryId: "de", city: "Munich", type: "Public",
    ranking: "37", priority: "High",
    ugAccepted: true, pgAccepted: true, minGpaUg: 2.5, minGpaPg: 3.0,
    ieltsRequired: true, ieltsOverall: 6.5,
    avgTuition: 0, scholarshipAvailable: true, scholarshipAmount: 0, scholarshipType: "Case-by-case",
    visaConfidence: "High", status: "Verified", updatedAt: now,
  },
];

export const seedPrograms: Program[] = [
  {
    id: "p-coventry-bsc-cs", name: "BSc Computer Science", universityId: "uk-coventry", level: "Undergraduate",
    faculty: "Engineering, Environment & Computing", category: "IT", duration: "3 years", placement: true,
    intakes: ["September", "January"], currency: "GBP", annualTuition: 16800, totalTuition: 50400,
    applicationFee: 0, scholarshipAvailable: true, scholarshipAmount: 4000,
    minGpa: 2.5, ieltsOverall: 6.0, moiAccepted: true,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-coventry-mba", name: "MBA", universityId: "uk-coventry", level: "MBA",
    faculty: "Business School", category: "Business", duration: "1 year",
    intakes: ["September", "January"], currency: "GBP", annualTuition: 19500, totalTuition: 19500,
    scholarshipAvailable: true, scholarshipAmount: 4000,
    minBachelor: 55, ieltsOverall: 6.5, moiAccepted: true,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-greenwich-msc-data", name: "MSc Data Science", universityId: "uk-greenwich", level: "Postgraduate",
    faculty: "Computing & Mathematical Sciences", category: "IT", duration: "1 year",
    intakes: ["September", "January"], currency: "GBP", annualTuition: 17500, totalTuition: 17500,
    scholarshipAvailable: true, scholarshipAmount: 3000,
    minBachelor: 55, ieltsOverall: 6.0, moiAccepted: true,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-deakin-mit", name: "Master of Information Technology", universityId: "au-deakin", level: "Postgraduate",
    faculty: "Science, Engineering & Built Env.", category: "IT", duration: "2 years",
    intakes: ["February", "July"], currency: "AUD", annualTuition: 38000, totalTuition: 76000,
    scholarshipAvailable: true, scholarshipAmount: 5000,
    minBachelor: 65, ieltsOverall: 6.5,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-deakin-mba", name: "Master of Business Administration", universityId: "au-deakin", level: "MBA",
    faculty: "Business & Law", category: "Business", duration: "2 years",
    intakes: ["February", "July"], currency: "AUD", annualTuition: 40000, totalTuition: 80000,
    minBachelor: 60, ieltsOverall: 6.5,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-latrobe-bnurs", name: "Bachelor of Nursing", universityId: "au-latrobe", level: "Undergraduate",
    faculty: "Health Sciences", category: "Health", duration: "3 years", placement: true,
    intakes: ["February", "July"], currency: "AUD", annualTuition: 34000, totalTuition: 102000,
    minPlus2: 60, ieltsOverall: 7.0,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-cbu-mba", name: "MBA in Community Economic Development", universityId: "ca-cape-breton", level: "MBA",
    faculty: "Business", category: "Business", duration: "2 years",
    intakes: ["January", "May", "September"], currency: "CAD", annualTuition: 21000, totalTuition: 42000,
    minBachelor: 55, ieltsOverall: 6.5,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-cbu-pgd-business", name: "PG Diploma in Business Management", universityId: "ca-cape-breton", level: "Diploma",
    faculty: "Business", category: "Business", duration: "1 year",
    intakes: ["January", "May", "September"], currency: "CAD", annualTuition: 15000, totalTuition: 15000,
    minBachelor: 50, ieltsOverall: 6.0,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-york-mscit", name: "Master of Information Systems & Tech.", universityId: "ca-york", level: "Postgraduate",
    faculty: "Schulich", category: "IT", duration: "1 year", currency: "CAD",
    intakes: ["September"], annualTuition: 32000, totalTuition: 32000, scholarshipAvailable: true, scholarshipAmount: 4000,
    minBachelor: 70, ieltsOverall: 6.5,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-asu-bscs", name: "BS in Computer Science", universityId: "us-asu", level: "Undergraduate",
    faculty: "Engineering", category: "IT", duration: "4 years", currency: "USD",
    intakes: ["August", "January"], annualTuition: 33000, totalTuition: 132000,
    scholarshipAvailable: true, scholarshipAmount: 8000,
    minPlus2: 70, ieltsOverall: 6.5,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-asu-mba", name: "Full-Time MBA", universityId: "us-asu", level: "MBA",
    faculty: "W. P. Carey", category: "Business", duration: "2 years", currency: "USD",
    intakes: ["August"], annualTuition: 60000, totalTuition: 120000,
    minBachelor: 70, ieltsOverall: 7.0,
    status: "Verified", updatedAt: now,
  },
  {
    id: "p-tum-mscse", name: "MSc Informatics", universityId: "de-tu-munich", level: "Postgraduate",
    faculty: "Informatics", category: "IT", duration: "2 years", currency: "EUR",
    intakes: ["October"], annualTuition: 0, totalTuition: 0,
    minBachelor: 70, ieltsOverall: 6.5,
    status: "Verified", updatedAt: now,
  },
];