/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CounselorRouteImport } from './routes/counselor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CounselorIndexRouteImport } from './routes/counselor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CounselorUniversitiesRouteImport } from './routes/counselor.universities'
import { Route as CounselorTrackerRouteImport } from './routes/counselor.tracker'
import { Route as CounselorStudentsRouteImport } from './routes/counselor.students'
import { Route as CounselorProgramsRouteImport } from './routes/counselor.programs'
import { Route as CounselorProcessRouteImport } from './routes/counselor.process'
import { Route as CounselorNotesRouteImport } from './routes/counselor.notes'
import { Route as CounselorMediaRouteImport } from './routes/counselor.media'
import { Route as CounselorMatcherRouteImport } from './routes/counselor.matcher'
import { Route as CounselorKnowledgeRouteImport } from './routes/counselor.knowledge'
import { Route as AdminUniversitiesRouteImport } from './routes/admin.universities'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequirementsRouteImport } from './routes/admin.requirements'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminProcessMapsRouteImport } from './routes/admin.process-maps'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminExcelRouteImport } from './routes/admin.excel'
import { Route as AdminCounselorsRouteImport } from './routes/admin.counselors'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as CounselorCountriesIndexRouteImport } from './routes/counselor.countries.index'
import { Route as AdminCountriesIndexRouteImport } from './routes/admin.countries.index'
import { Route as CounselorProgramsProgramIdRouteImport } from './routes/counselor.programs.$programId'
import { Route as CounselorCountriesCountryIdRouteImport } from './routes/counselor.countries.$countryId'
import { Route as AdminCountriesCountryIdRouteImport } from './routes/admin.countries.$countryId'
import { Route as CounselorCountriesCountryIdUniversitiesUniversityIdRouteImport } from './routes/counselor.countries.$countryId.universities.$universityId'
import { Route as AdminCountriesCountryIdUniversitiesUniversityIdRouteImport } from './routes/admin.countries.$countryId.universities.$universityId'

const CounselorRoute = CounselorRouteImport.update({
  id: '/counselor',
  path: '/counselor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorIndexRoute = CounselorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CounselorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CounselorUniversitiesRoute = CounselorUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorTrackerRoute = CounselorTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorStudentsRoute = CounselorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorProgramsRoute = CounselorProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorProcessRoute = CounselorProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorNotesRoute = CounselorNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorMediaRoute = CounselorMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorMatcherRoute = CounselorMatcherRouteImport.update({
  id: '/matcher',
  path: '/matcher',
  getParentRoute: () => CounselorRoute,
} as any)
const CounselorKnowledgeRoute = CounselorKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => CounselorRoute,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequirementsRoute = AdminRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessMapsRoute = AdminProcessMapsRouteImport.update({
  id: '/process-maps',
  path: '/process-maps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExcelRoute = AdminExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCounselorsRoute = AdminCounselorsRouteImport.update({
  id: '/counselors',
  path: '/counselors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const CounselorCountriesIndexRoute = CounselorCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => CounselorRoute,
} as any)
const AdminCountriesIndexRoute = AdminCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => AdminRoute,
} as any)
const CounselorProgramsProgramIdRoute =
  CounselorProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => CounselorProgramsRoute,
  } as any)
const CounselorCountriesCountryIdRoute =
  CounselorCountriesCountryIdRouteImport.update({
    id: '/countries/$countryId',
    path: '/countries/$countryId',
    getParentRoute: () => CounselorRoute,
  } as any)
const AdminCountriesCountryIdRoute = AdminCountriesCountryIdRouteImport.update({
  id: '/countries/$countryId',
  path: '/countries/$countryId',
  getParentRoute: () => AdminRoute,
} as any)
const CounselorCountriesCountryIdUniversitiesUniversityIdRoute =
  CounselorCountriesCountryIdUniversitiesUniversityIdRouteImport.update({
    id: '/universities/$universityId',
    path: '/universities/$universityId',
    getParentRoute: () => CounselorCountriesCountryIdRoute,
  } as any)
const AdminCountriesCountryIdUniversitiesUniversityIdRoute =
  AdminCountriesCountryIdUniversitiesUniversityIdRouteImport.update({
    id: '/universities/$universityId',
    path: '/universities/$universityId',
    getParentRoute: () => AdminCountriesCountryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/counselor': typeof CounselorRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/excel': typeof AdminExcelRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/process-maps': typeof AdminProcessMapsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/requirements': typeof AdminRequirementsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/counselor/knowledge': typeof CounselorKnowledgeRoute
  '/counselor/matcher': typeof CounselorMatcherRoute
  '/counselor/media': typeof CounselorMediaRoute
  '/counselor/notes': typeof CounselorNotesRoute
  '/counselor/process': typeof CounselorProcessRoute
  '/counselor/programs': typeof CounselorProgramsRouteWithChildren
  '/counselor/students': typeof CounselorStudentsRoute
  '/counselor/tracker': typeof CounselorTrackerRoute
  '/counselor/universities': typeof CounselorUniversitiesRoute
  '/admin/': typeof AdminIndexRoute
  '/counselor/': typeof CounselorIndexRoute
  '/admin/countries/$countryId': typeof AdminCountriesCountryIdRouteWithChildren
  '/counselor/countries/$countryId': typeof CounselorCountriesCountryIdRouteWithChildren
  '/counselor/programs/$programId': typeof CounselorProgramsProgramIdRoute
  '/admin/countries/': typeof AdminCountriesIndexRoute
  '/counselor/countries/': typeof CounselorCountriesIndexRoute
  '/admin/countries/$countryId/universities/$universityId': typeof AdminCountriesCountryIdUniversitiesUniversityIdRoute
  '/counselor/countries/$countryId/universities/$universityId': typeof CounselorCountriesCountryIdUniversitiesUniversityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/excel': typeof AdminExcelRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/process-maps': typeof AdminProcessMapsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/requirements': typeof AdminRequirementsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/counselor/knowledge': typeof CounselorKnowledgeRoute
  '/counselor/matcher': typeof CounselorMatcherRoute
  '/counselor/media': typeof CounselorMediaRoute
  '/counselor/notes': typeof CounselorNotesRoute
  '/counselor/process': typeof CounselorProcessRoute
  '/counselor/programs': typeof CounselorProgramsRouteWithChildren
  '/counselor/students': typeof CounselorStudentsRoute
  '/counselor/tracker': typeof CounselorTrackerRoute
  '/counselor/universities': typeof CounselorUniversitiesRoute
  '/admin': typeof AdminIndexRoute
  '/counselor': typeof CounselorIndexRoute
  '/admin/countries/$countryId': typeof AdminCountriesCountryIdRouteWithChildren
  '/counselor/countries/$countryId': typeof CounselorCountriesCountryIdRouteWithChildren
  '/counselor/programs/$programId': typeof CounselorProgramsProgramIdRoute
  '/admin/countries': typeof AdminCountriesIndexRoute
  '/counselor/countries': typeof CounselorCountriesIndexRoute
  '/admin/countries/$countryId/universities/$universityId': typeof AdminCountriesCountryIdUniversitiesUniversityIdRoute
  '/counselor/countries/$countryId/universities/$universityId': typeof CounselorCountriesCountryIdUniversitiesUniversityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/counselor': typeof CounselorRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/counselors': typeof AdminCounselorsRoute
  '/admin/excel': typeof AdminExcelRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/process-maps': typeof AdminProcessMapsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/requirements': typeof AdminRequirementsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/counselor/knowledge': typeof CounselorKnowledgeRoute
  '/counselor/matcher': typeof CounselorMatcherRoute
  '/counselor/media': typeof CounselorMediaRoute
  '/counselor/notes': typeof CounselorNotesRoute
  '/counselor/process': typeof CounselorProcessRoute
  '/counselor/programs': typeof CounselorProgramsRouteWithChildren
  '/counselor/students': typeof CounselorStudentsRoute
  '/counselor/tracker': typeof CounselorTrackerRoute
  '/counselor/universities': typeof CounselorUniversitiesRoute
  '/admin/': typeof AdminIndexRoute
  '/counselor/': typeof CounselorIndexRoute
  '/admin/countries/$countryId': typeof AdminCountriesCountryIdRouteWithChildren
  '/counselor/countries/$countryId': typeof CounselorCountriesCountryIdRouteWithChildren
  '/counselor/programs/$programId': typeof CounselorProgramsProgramIdRoute
  '/admin/countries/': typeof AdminCountriesIndexRoute
  '/counselor/countries/': typeof CounselorCountriesIndexRoute
  '/admin/countries/$countryId/universities/$universityId': typeof AdminCountriesCountryIdUniversitiesUniversityIdRoute
  '/counselor/countries/$countryId/universities/$universityId': typeof CounselorCountriesCountryIdUniversitiesUniversityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/counselor'
    | '/admin/audit'
    | '/admin/counselors'
    | '/admin/excel'
    | '/admin/fees'
    | '/admin/media'
    | '/admin/notes'
    | '/admin/process-maps'
    | '/admin/programs'
    | '/admin/requirements'
    | '/admin/settings'
    | '/admin/universities'
    | '/counselor/knowledge'
    | '/counselor/matcher'
    | '/counselor/media'
    | '/counselor/notes'
    | '/counselor/process'
    | '/counselor/programs'
    | '/counselor/students'
    | '/counselor/tracker'
    | '/counselor/universities'
    | '/admin/'
    | '/counselor/'
    | '/admin/countries/$countryId'
    | '/counselor/countries/$countryId'
    | '/counselor/programs/$programId'
    | '/admin/countries/'
    | '/counselor/countries/'
    | '/admin/countries/$countryId/universities/$universityId'
    | '/counselor/countries/$countryId/universities/$universityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/counselors'
    | '/admin/excel'
    | '/admin/fees'
    | '/admin/media'
    | '/admin/notes'
    | '/admin/process-maps'
    | '/admin/programs'
    | '/admin/requirements'
    | '/admin/settings'
    | '/admin/universities'
    | '/counselor/knowledge'
    | '/counselor/matcher'
    | '/counselor/media'
    | '/counselor/notes'
    | '/counselor/process'
    | '/counselor/programs'
    | '/counselor/students'
    | '/counselor/tracker'
    | '/counselor/universities'
    | '/admin'
    | '/counselor'
    | '/admin/countries/$countryId'
    | '/counselor/countries/$countryId'
    | '/counselor/programs/$programId'
    | '/admin/countries'
    | '/counselor/countries'
    | '/admin/countries/$countryId/universities/$universityId'
    | '/counselor/countries/$countryId/universities/$universityId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/counselor'
    | '/admin/audit'
    | '/admin/counselors'
    | '/admin/excel'
    | '/admin/fees'
    | '/admin/media'
    | '/admin/notes'
    | '/admin/process-maps'
    | '/admin/programs'
    | '/admin/requirements'
    | '/admin/settings'
    | '/admin/universities'
    | '/counselor/knowledge'
    | '/counselor/matcher'
    | '/counselor/media'
    | '/counselor/notes'
    | '/counselor/process'
    | '/counselor/programs'
    | '/counselor/students'
    | '/counselor/tracker'
    | '/counselor/universities'
    | '/admin/'
    | '/counselor/'
    | '/admin/countries/$countryId'
    | '/counselor/countries/$countryId'
    | '/counselor/programs/$programId'
    | '/admin/countries/'
    | '/counselor/countries/'
    | '/admin/countries/$countryId/universities/$universityId'
    | '/counselor/countries/$countryId/universities/$universityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CounselorRoute: typeof CounselorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/counselor': {
      id: '/counselor'
      path: '/counselor'
      fullPath: '/counselor'
      preLoaderRoute: typeof CounselorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselor/': {
      id: '/counselor/'
      path: '/'
      fullPath: '/counselor/'
      preLoaderRoute: typeof CounselorIndexRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/counselor/universities': {
      id: '/counselor/universities'
      path: '/universities'
      fullPath: '/counselor/universities'
      preLoaderRoute: typeof CounselorUniversitiesRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/tracker': {
      id: '/counselor/tracker'
      path: '/tracker'
      fullPath: '/counselor/tracker'
      preLoaderRoute: typeof CounselorTrackerRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/students': {
      id: '/counselor/students'
      path: '/students'
      fullPath: '/counselor/students'
      preLoaderRoute: typeof CounselorStudentsRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/programs': {
      id: '/counselor/programs'
      path: '/programs'
      fullPath: '/counselor/programs'
      preLoaderRoute: typeof CounselorProgramsRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/process': {
      id: '/counselor/process'
      path: '/process'
      fullPath: '/counselor/process'
      preLoaderRoute: typeof CounselorProcessRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/notes': {
      id: '/counselor/notes'
      path: '/notes'
      fullPath: '/counselor/notes'
      preLoaderRoute: typeof CounselorNotesRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/media': {
      id: '/counselor/media'
      path: '/media'
      fullPath: '/counselor/media'
      preLoaderRoute: typeof CounselorMediaRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/matcher': {
      id: '/counselor/matcher'
      path: '/matcher'
      fullPath: '/counselor/matcher'
      preLoaderRoute: typeof CounselorMatcherRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/counselor/knowledge': {
      id: '/counselor/knowledge'
      path: '/knowledge'
      fullPath: '/counselor/knowledge'
      preLoaderRoute: typeof CounselorKnowledgeRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/admin/universities': {
      id: '/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requirements': {
      id: '/admin/requirements'
      path: '/requirements'
      fullPath: '/admin/requirements'
      preLoaderRoute: typeof AdminRequirementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/process-maps': {
      id: '/admin/process-maps'
      path: '/process-maps'
      fullPath: '/admin/process-maps'
      preLoaderRoute: typeof AdminProcessMapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/excel': {
      id: '/admin/excel'
      path: '/excel'
      fullPath: '/admin/excel'
      preLoaderRoute: typeof AdminExcelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/counselors': {
      id: '/admin/counselors'
      path: '/counselors'
      fullPath: '/admin/counselors'
      preLoaderRoute: typeof AdminCounselorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/counselor/countries/': {
      id: '/counselor/countries/'
      path: '/countries'
      fullPath: '/counselor/countries/'
      preLoaderRoute: typeof CounselorCountriesIndexRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/admin/countries/': {
      id: '/admin/countries/'
      path: '/countries'
      fullPath: '/admin/countries/'
      preLoaderRoute: typeof AdminCountriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/counselor/programs/$programId': {
      id: '/counselor/programs/$programId'
      path: '/$programId'
      fullPath: '/counselor/programs/$programId'
      preLoaderRoute: typeof CounselorProgramsProgramIdRouteImport
      parentRoute: typeof CounselorProgramsRoute
    }
    '/counselor/countries/$countryId': {
      id: '/counselor/countries/$countryId'
      path: '/countries/$countryId'
      fullPath: '/counselor/countries/$countryId'
      preLoaderRoute: typeof CounselorCountriesCountryIdRouteImport
      parentRoute: typeof CounselorRoute
    }
    '/admin/countries/$countryId': {
      id: '/admin/countries/$countryId'
      path: '/countries/$countryId'
      fullPath: '/admin/countries/$countryId'
      preLoaderRoute: typeof AdminCountriesCountryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/counselor/countries/$countryId/universities/$universityId': {
      id: '/counselor/countries/$countryId/universities/$universityId'
      path: '/universities/$universityId'
      fullPath: '/counselor/countries/$countryId/universities/$universityId'
      preLoaderRoute: typeof CounselorCountriesCountryIdUniversitiesUniversityIdRouteImport
      parentRoute: typeof CounselorCountriesCountryIdRoute
    }
    '/admin/countries/$countryId/universities/$universityId': {
      id: '/admin/countries/$countryId/universities/$universityId'
      path: '/universities/$universityId'
      fullPath: '/admin/countries/$countryId/universities/$universityId'
      preLoaderRoute: typeof AdminCountriesCountryIdUniversitiesUniversityIdRouteImport
      parentRoute: typeof AdminCountriesCountryIdRoute
    }
  }
}

interface AdminCountriesCountryIdRouteChildren {
  AdminCountriesCountryIdUniversitiesUniversityIdRoute: typeof AdminCountriesCountryIdUniversitiesUniversityIdRoute
}

const AdminCountriesCountryIdRouteChildren: AdminCountriesCountryIdRouteChildren =
  {
    AdminCountriesCountryIdUniversitiesUniversityIdRoute:
      AdminCountriesCountryIdUniversitiesUniversityIdRoute,
  }

const AdminCountriesCountryIdRouteWithChildren =
  AdminCountriesCountryIdRoute._addFileChildren(
    AdminCountriesCountryIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCounselorsRoute: typeof AdminCounselorsRoute
  AdminExcelRoute: typeof AdminExcelRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminProcessMapsRoute: typeof AdminProcessMapsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminRequirementsRoute: typeof AdminRequirementsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCountriesCountryIdRoute: typeof AdminCountriesCountryIdRouteWithChildren
  AdminCountriesIndexRoute: typeof AdminCountriesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCounselorsRoute: AdminCounselorsRoute,
  AdminExcelRoute: AdminExcelRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminProcessMapsRoute: AdminProcessMapsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminRequirementsRoute: AdminRequirementsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCountriesCountryIdRoute: AdminCountriesCountryIdRouteWithChildren,
  AdminCountriesIndexRoute: AdminCountriesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CounselorProgramsRouteChildren {
  CounselorProgramsProgramIdRoute: typeof CounselorProgramsProgramIdRoute
}

const CounselorProgramsRouteChildren: CounselorProgramsRouteChildren = {
  CounselorProgramsProgramIdRoute: CounselorProgramsProgramIdRoute,
}

const CounselorProgramsRouteWithChildren =
  CounselorProgramsRoute._addFileChildren(CounselorProgramsRouteChildren)

interface CounselorCountriesCountryIdRouteChildren {
  CounselorCountriesCountryIdUniversitiesUniversityIdRoute: typeof CounselorCountriesCountryIdUniversitiesUniversityIdRoute
}

const CounselorCountriesCountryIdRouteChildren: CounselorCountriesCountryIdRouteChildren =
  {
    CounselorCountriesCountryIdUniversitiesUniversityIdRoute:
      CounselorCountriesCountryIdUniversitiesUniversityIdRoute,
  }

const CounselorCountriesCountryIdRouteWithChildren =
  CounselorCountriesCountryIdRoute._addFileChildren(
    CounselorCountriesCountryIdRouteChildren,
  )

interface CounselorRouteChildren {
  CounselorKnowledgeRoute: typeof CounselorKnowledgeRoute
  CounselorMatcherRoute: typeof CounselorMatcherRoute
  CounselorMediaRoute: typeof CounselorMediaRoute
  CounselorNotesRoute: typeof CounselorNotesRoute
  CounselorProcessRoute: typeof CounselorProcessRoute
  CounselorProgramsRoute: typeof CounselorProgramsRouteWithChildren
  CounselorStudentsRoute: typeof CounselorStudentsRoute
  CounselorTrackerRoute: typeof CounselorTrackerRoute
  CounselorUniversitiesRoute: typeof CounselorUniversitiesRoute
  CounselorIndexRoute: typeof CounselorIndexRoute
  CounselorCountriesCountryIdRoute: typeof CounselorCountriesCountryIdRouteWithChildren
  CounselorCountriesIndexRoute: typeof CounselorCountriesIndexRoute
}

const CounselorRouteChildren: CounselorRouteChildren = {
  CounselorKnowledgeRoute: CounselorKnowledgeRoute,
  CounselorMatcherRoute: CounselorMatcherRoute,
  CounselorMediaRoute: CounselorMediaRoute,
  CounselorNotesRoute: CounselorNotesRoute,
  CounselorProcessRoute: CounselorProcessRoute,
  CounselorProgramsRoute: CounselorProgramsRouteWithChildren,
  CounselorStudentsRoute: CounselorStudentsRoute,
  CounselorTrackerRoute: CounselorTrackerRoute,
  CounselorUniversitiesRoute: CounselorUniversitiesRoute,
  CounselorIndexRoute: CounselorIndexRoute,
  CounselorCountriesCountryIdRoute:
    CounselorCountriesCountryIdRouteWithChildren,
  CounselorCountriesIndexRoute: CounselorCountriesIndexRoute,
}

const CounselorRouteWithChildren = CounselorRoute._addFileChildren(
  CounselorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CounselorRoute: CounselorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
